services:
    Octopouce\CmsBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Resources}'
        autowire: true
        autoconfigure: true
        public: false

    Octopouce\CmsBundle\EventListener\PageUploadListener:
        autowire: true
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }